/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlternativeNamesCopy200ResponseLogosInner } from './alternativeNamesCopy200ResponseLogosInner';


export interface AlternativeNamesCopy200Response { 
    id?: number;
    logos?: Array<AlternativeNamesCopy200ResponseLogosInner>;
}

