/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificationMovieList200ResponseCertifications } from './certificationMovieList200ResponseCertifications';


export interface CertificationMovieList200Response { 
    certifications?: CertificationMovieList200ResponseCertifications;
}

