/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificationsTvList200ResponseCertifications } from './certificationsTvList200ResponseCertifications';


export interface CertificationsTvList200Response { 
    certifications?: CertificationsTvList200ResponseCertifications;
}

