/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificationMovieList200ResponseCertificationsTWInner } from './certificationMovieList200ResponseCertificationsTWInner';
import { CertificationMovieList200ResponseCertificationsZAInner } from './certificationMovieList200ResponseCertificationsZAInner';
import { CertificationMovieList200ResponseCertificationsPRInner } from './certificationMovieList200ResponseCertificationsPRInner';
import { CertificationMovieList200ResponseCertificationsBGInner } from './certificationMovieList200ResponseCertificationsBGInner';
import { CertificationMovieList200ResponseCertificationsFIInner } from './certificationMovieList200ResponseCertificationsFIInner';
import { CertificationMovieList200ResponseCertificationsLVInner } from './certificationMovieList200ResponseCertificationsLVInner';
import { CertificationMovieList200ResponseCertificationsFRInner } from './certificationMovieList200ResponseCertificationsFRInner';
import { CertificationMovieList200ResponseCertificationsIDInner } from './certificationMovieList200ResponseCertificationsIDInner';
import { CertificationMovieList200ResponseCertificationsILInner } from './certificationMovieList200ResponseCertificationsILInner';
import { CertificationMovieList200ResponseCertificationsTHInner } from './certificationMovieList200ResponseCertificationsTHInner';
import { CertificationMovieList200ResponseCertificationsSGInner } from './certificationMovieList200ResponseCertificationsSGInner';
import { CertificationMovieList200ResponseCertificationsUSInner } from './certificationMovieList200ResponseCertificationsUSInner';
import { CertificationMovieList200ResponseCertificationsCHInner } from './certificationMovieList200ResponseCertificationsCHInner';
import { CertificationMovieList200ResponseCertificationsHKInner } from './certificationMovieList200ResponseCertificationsHKInner';
import { CertificationMovieList200ResponseCertificationsKRInner } from './certificationMovieList200ResponseCertificationsKRInner';
import { CertificationMovieList200ResponseCertificationsBRInner } from './certificationMovieList200ResponseCertificationsBRInner';
import { CertificationMovieList200ResponseCertificationsGBInner } from './certificationMovieList200ResponseCertificationsGBInner';
import { CertificationMovieList200ResponseCertificationsNOInner } from './certificationMovieList200ResponseCertificationsNOInner';
import { CertificationMovieList200ResponseCertificationsSEInner } from './certificationMovieList200ResponseCertificationsSEInner';
import { CertificationMovieList200ResponseCertificationsJPInner } from './certificationMovieList200ResponseCertificationsJPInner';
import { CertificationMovieList200ResponseCertificationsTRInner } from './certificationMovieList200ResponseCertificationsTRInner';
import { CertificationMovieList200ResponseCertificationsAUInner } from './certificationMovieList200ResponseCertificationsAUInner';
import { CertificationMovieList200ResponseCertificationsCAQCInner } from './certificationMovieList200ResponseCertificationsCAQCInner';
import { CertificationMovieList200ResponseCertificationsGRInner } from './certificationMovieList200ResponseCertificationsGRInner';
import { CertificationMovieList200ResponseCertificationsARInner } from './certificationMovieList200ResponseCertificationsARInner';
import { CertificationMovieList200ResponseCertificationsPTInner } from './certificationMovieList200ResponseCertificationsPTInner';
import { CertificationMovieList200ResponseCertificationsESInner } from './certificationMovieList200ResponseCertificationsESInner';
import { CertificationMovieList200ResponseCertificationsIEInner } from './certificationMovieList200ResponseCertificationsIEInner';
import { CertificationMovieList200ResponseCertificationsSKInner } from './certificationMovieList200ResponseCertificationsSKInner';
import { CertificationMovieList200ResponseCertificationsINInner } from './certificationMovieList200ResponseCertificationsINInner';
import { CertificationMovieList200ResponseCertificationsNZInner } from './certificationMovieList200ResponseCertificationsNZInner';
import { CertificationMovieList200ResponseCertificationsDEInner } from './certificationMovieList200ResponseCertificationsDEInner';
import { CertificationMovieList200ResponseCertificationsCAInner } from './certificationMovieList200ResponseCertificationsCAInner';
import { CertificationMovieList200ResponseCertificationsVIInner } from './certificationMovieList200ResponseCertificationsVIInner';
import { CertificationMovieList200ResponseCertificationsLUInner } from './certificationMovieList200ResponseCertificationsLUInner';
import { CertificationMovieList200ResponseCertificationsNLInner } from './certificationMovieList200ResponseCertificationsNLInner';
import { CertificationMovieList200ResponseCertificationsMXInner } from './certificationMovieList200ResponseCertificationsMXInner';
import { CertificationMovieList200ResponseCertificationsHUInner } from './certificationMovieList200ResponseCertificationsHUInner';
import { CertificationMovieList200ResponseCertificationsRUInner } from './certificationMovieList200ResponseCertificationsRUInner';
import { CertificationMovieList200ResponseCertificationsMOInner } from './certificationMovieList200ResponseCertificationsMOInner';


export interface CertificationMovieList200ResponseCertifications { 
    AU?: Array<CertificationMovieList200ResponseCertificationsAUInner>;
    BG?: Array<CertificationMovieList200ResponseCertificationsBGInner>;
    BR?: Array<CertificationMovieList200ResponseCertificationsBRInner>;
    CA?: Array<CertificationMovieList200ResponseCertificationsCAInner>;
    CA_QC?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    DE?: Array<CertificationMovieList200ResponseCertificationsDEInner>;
    DK?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    ES?: Array<CertificationMovieList200ResponseCertificationsESInner>;
    FI?: Array<CertificationMovieList200ResponseCertificationsFIInner>;
    FR?: Array<CertificationMovieList200ResponseCertificationsFRInner>;
    GB?: Array<CertificationMovieList200ResponseCertificationsGBInner>;
    HU?: Array<CertificationMovieList200ResponseCertificationsHUInner>;
    IN?: Array<CertificationMovieList200ResponseCertificationsINInner>;
    IT?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    LT?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    MY?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    NL?: Array<CertificationMovieList200ResponseCertificationsNLInner>;
    NO?: Array<CertificationMovieList200ResponseCertificationsNOInner>;
    NZ?: Array<CertificationMovieList200ResponseCertificationsNZInner>;
    PH?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    PT?: Array<CertificationMovieList200ResponseCertificationsPTInner>;
    RU?: Array<CertificationMovieList200ResponseCertificationsRUInner>;
    SE?: Array<CertificationMovieList200ResponseCertificationsSEInner>;
    US?: Array<CertificationMovieList200ResponseCertificationsUSInner>;
    KR?: Array<CertificationMovieList200ResponseCertificationsKRInner>;
    SK?: Array<CertificationMovieList200ResponseCertificationsSKInner>;
    TH?: Array<CertificationMovieList200ResponseCertificationsTHInner>;
    MX?: Array<CertificationMovieList200ResponseCertificationsMXInner>;
    ID?: Array<CertificationMovieList200ResponseCertificationsIDInner>;
    TR?: Array<CertificationMovieList200ResponseCertificationsTRInner>;
    AR?: Array<CertificationMovieList200ResponseCertificationsARInner>;
    GR?: Array<CertificationMovieList200ResponseCertificationsGRInner>;
    TW?: Array<CertificationMovieList200ResponseCertificationsTWInner>;
    ZA?: Array<CertificationMovieList200ResponseCertificationsZAInner>;
    SG?: Array<CertificationMovieList200ResponseCertificationsSGInner>;
    IE?: Array<CertificationMovieList200ResponseCertificationsIEInner>;
    PR?: Array<CertificationMovieList200ResponseCertificationsPRInner>;
    JP?: Array<CertificationMovieList200ResponseCertificationsJPInner>;
    VI?: Array<CertificationMovieList200ResponseCertificationsVIInner>;
    CH?: Array<CertificationMovieList200ResponseCertificationsCHInner>;
    IL?: Array<CertificationMovieList200ResponseCertificationsILInner>;
    HK?: Array<CertificationMovieList200ResponseCertificationsHKInner>;
    MO?: Array<CertificationMovieList200ResponseCertificationsMOInner>;
    LV?: Array<CertificationMovieList200ResponseCertificationsLVInner>;
    LU?: Array<CertificationMovieList200ResponseCertificationsLUInner>;
}

