/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificationsTvList200ResponseCertificationsITInner } from './certificationsTvList200ResponseCertificationsITInner';
import { CertificationsTvList200ResponseCertificationsDKInner } from './certificationsTvList200ResponseCertificationsDKInner';
import { CertificationsTvList200ResponseCertificationsINInner } from './certificationsTvList200ResponseCertificationsINInner';
import { CertificationsTvList200ResponseCertificationsNZInner } from './certificationsTvList200ResponseCertificationsNZInner';
import { CertificationsTvList200ResponseCertificationsDEInner } from './certificationsTvList200ResponseCertificationsDEInner';
import { CertificationMovieList200ResponseCertificationsPRInner } from './certificationMovieList200ResponseCertificationsPRInner';
import { CertificationsTvList200ResponseCertificationsMAInner } from './certificationsTvList200ResponseCertificationsMAInner';
import { CertificationsTvList200ResponseCertificationsCAInner } from './certificationsTvList200ResponseCertificationsCAInner';
import { CertificationsTvList200ResponseCertificationsMYInner } from './certificationsTvList200ResponseCertificationsMYInner';
import { CertificationsTvList200ResponseCertificationsCAQCInner } from './certificationsTvList200ResponseCertificationsCAQCInner';
import { CertificationsTvList200ResponseCertificationsILInner } from './certificationsTvList200ResponseCertificationsILInner';
import { CertificationsTvList200ResponseCertificationsNOInner } from './certificationsTvList200ResponseCertificationsNOInner';
import { CertificationMovieList200ResponseCertificationsCAQCInner } from './certificationMovieList200ResponseCertificationsCAQCInner';
import { CertificationsTvList200ResponseCertificationsLTInner } from './certificationsTvList200ResponseCertificationsLTInner';
import { CertificationsTvList200ResponseCertificationsPLInner } from './certificationsTvList200ResponseCertificationsPLInner';
import { CertificationsTvList200ResponseCertificationsPRInner } from './certificationsTvList200ResponseCertificationsPRInner';
import { CertificationsTvList200ResponseCertificationsTWInner } from './certificationsTvList200ResponseCertificationsTWInner';
import { CertificationsTvList200ResponseCertificationsHUInner } from './certificationsTvList200ResponseCertificationsHUInner';
import { CertificationsTvList200ResponseCertificationsMXInner } from './certificationsTvList200ResponseCertificationsMXInner';
import { CertificationsTvList200ResponseCertificationsKRInner } from './certificationsTvList200ResponseCertificationsKRInner';
import { CertificationsTvList200ResponseCertificationsBGInner } from './certificationsTvList200ResponseCertificationsBGInner';
import { CertificationsTvList200ResponseCertificationsFIInner } from './certificationsTvList200ResponseCertificationsFIInner';
import { CertificationsTvList200ResponseCertificationsIDInner } from './certificationsTvList200ResponseCertificationsIDInner';
import { CertificationsTvList200ResponseCertificationsRUInner } from './certificationsTvList200ResponseCertificationsRUInner';
import { CertificationsTvList200ResponseCertificationsUSInner } from './certificationsTvList200ResponseCertificationsUSInner';
import { CertificationsTvList200ResponseCertificationsTHInner } from './certificationsTvList200ResponseCertificationsTHInner';
import { CertificationsTvList200ResponseCertificationsZAInner } from './certificationsTvList200ResponseCertificationsZAInner';
import { CertificationsTvList200ResponseCertificationsARInner } from './certificationsTvList200ResponseCertificationsARInner';
import { CertificationsTvList200ResponseCertificationsSEInner } from './certificationsTvList200ResponseCertificationsSEInner';
import { CertificationsTvList200ResponseCertificationsTRInner } from './certificationsTvList200ResponseCertificationsTRInner';
import { CertificationsTvList200ResponseCertificationsAUInner } from './certificationsTvList200ResponseCertificationsAUInner';
import { CertificationsTvList200ResponseCertificationsBRInner } from './certificationsTvList200ResponseCertificationsBRInner';
import { CertificationsTvList200ResponseCertificationsPTInner } from './certificationsTvList200ResponseCertificationsPTInner';
import { CertificationsTvList200ResponseCertificationsGRInner } from './certificationsTvList200ResponseCertificationsGRInner';
import { CertificationsTvList200ResponseCertificationsGBInner } from './certificationsTvList200ResponseCertificationsGBInner';


export interface CertificationsTvList200ResponseCertifications { 
    AU?: Array<CertificationsTvList200ResponseCertificationsAUInner>;
    BR?: Array<CertificationsTvList200ResponseCertificationsBRInner>;
    CA?: Array<CertificationsTvList200ResponseCertificationsCAInner>;
    CA_QC?: Array<CertificationsTvList200ResponseCertificationsCAQCInner>;
    DE?: Array<CertificationsTvList200ResponseCertificationsDEInner>;
    ES?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    FR?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    GB?: Array<CertificationsTvList200ResponseCertificationsGBInner>;
    HU?: Array<CertificationsTvList200ResponseCertificationsHUInner>;
    KR?: Array<CertificationsTvList200ResponseCertificationsKRInner>;
    LT?: Array<CertificationsTvList200ResponseCertificationsLTInner>;
    NL?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    PH?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    PT?: Array<CertificationsTvList200ResponseCertificationsPTInner>;
    RU?: Array<CertificationsTvList200ResponseCertificationsRUInner>;
    SK?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    TH?: Array<CertificationsTvList200ResponseCertificationsTHInner>;
    US?: Array<CertificationsTvList200ResponseCertificationsUSInner>;
    IT?: Array<CertificationsTvList200ResponseCertificationsITInner>;
    FI?: Array<CertificationsTvList200ResponseCertificationsFIInner>;
    MY?: Array<CertificationsTvList200ResponseCertificationsMYInner>;
    NZ?: Array<CertificationsTvList200ResponseCertificationsNZInner>;
    NO?: Array<CertificationsTvList200ResponseCertificationsNOInner>;
    BG?: Array<CertificationsTvList200ResponseCertificationsBGInner>;
    MX?: Array<CertificationsTvList200ResponseCertificationsMXInner>;
    IN?: Array<CertificationsTvList200ResponseCertificationsINInner>;
    DK?: Array<CertificationsTvList200ResponseCertificationsDKInner>;
    SE?: Array<CertificationsTvList200ResponseCertificationsSEInner>;
    ID?: Array<CertificationsTvList200ResponseCertificationsIDInner>;
    TR?: Array<CertificationsTvList200ResponseCertificationsTRInner>;
    AR?: Array<CertificationsTvList200ResponseCertificationsARInner>;
    PL?: Array<CertificationsTvList200ResponseCertificationsPLInner>;
    MA?: Array<CertificationsTvList200ResponseCertificationsMAInner>;
    GR?: Array<CertificationsTvList200ResponseCertificationsGRInner>;
    IL?: Array<CertificationsTvList200ResponseCertificationsILInner>;
    TW?: Array<CertificationsTvList200ResponseCertificationsTWInner>;
    ZA?: Array<CertificationsTvList200ResponseCertificationsZAInner>;
    SG?: Array<CertificationMovieList200ResponseCertificationsPRInner>;
    PR?: Array<CertificationsTvList200ResponseCertificationsPRInner>;
    VI?: Array<CertificationsTvList200ResponseCertificationsPRInner>;
}

