/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangesTvList200ResponseResultsInner } from './changesTvList200ResponseResultsInner';


export interface ChangesTvList200Response { 
    results?: Array<ChangesTvList200ResponseResultsInner>;
    page?: number;
    total_pages?: number;
    total_results?: number;
}

