/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangesPeopleList200ResponseResultsInner } from './changesPeopleList200ResponseResultsInner';


export interface ChangesPeopleList200Response { 
    results?: Array<ChangesPeopleList200ResponseResultsInner>;
    page?: number;
    total_pages?: number;
    total_results?: number;
}

