/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangesMovieList200ResponseResultsInner } from './changesMovieList200ResponseResultsInner';


export interface ChangesMovieList200Response { 
    results?: Array<ChangesMovieList200ResponseResultsInner>;
    page?: number;
    total_pages?: number;
    total_results?: number;
}

