/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionTranslations200ResponseTranslationsInner } from './collectionTranslations200ResponseTranslationsInner';


export interface CollectionTranslations200Response { 
    id?: number;
    translations?: Array<CollectionTranslations200ResponseTranslationsInner>;
}

