/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyImages200ResponseLogosInner } from './companyImages200ResponseLogosInner';


export interface CompanyImages200Response { 
    id?: number;
    logos?: Array<CompanyImages200ResponseLogosInner>;
}

