/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDetails200ResponseImages } from './configurationDetails200ResponseImages';


export interface ConfigurationDetails200Response { 
    images?: ConfigurationDetails200ResponseImages;
    change_keys?: Array<string>;
}

