/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditDetails200ResponsePerson } from './creditDetails200ResponsePerson';
import { CreditDetails200ResponseMedia } from './creditDetails200ResponseMedia';


export interface CreditDetails200Response { 
    credit_type?: string;
    department?: string;
    job?: string;
    media?: CreditDetails200ResponseMedia;
    media_type?: string;
    id?: string;
    person?: CreditDetails200ResponsePerson;
}

