/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetailsCopy200ResponseResultsInner } from './detailsCopy200ResponseResultsInner';


export interface DetailsCopy200Response { 
    id?: number;
    results?: Array<DetailsCopy200ResponseResultsInner>;
}

