/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenreTvList200ResponseGenresInner } from './genreTvList200ResponseGenresInner';


export interface GenreTvList200Response { 
    genres?: Array<GenreTvList200ResponseGenresInner>;
}

