/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenreMovieList200ResponseGenresInner } from './genreMovieList200ResponseGenresInner';


export interface GenreMovieList200Response { 
    genres?: Array<GenreMovieList200ResponseGenresInner>;
}

