/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestSessionRatedTvEpisodes200ResponseResultsInner } from './guestSessionRatedTvEpisodes200ResponseResultsInner';


export interface GuestSessionRatedTvEpisodes200Response { 
    page?: number;
    results?: Array<GuestSessionRatedTvEpisodes200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

