/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListDetails200ResponseItemsInner } from './listDetails200ResponseItemsInner';


export interface ListDetails200Response { 
    created_by?: string;
    description?: string;
    favorite_count?: number;
    id?: string;
    items?: Array<ListDetails200ResponseItemsInner>;
    item_count?: number;
    iso_639_1?: string;
    name?: string;
    poster_path?: string;
}

