/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsBHBuyInner } from './movieWatchProviders200ResponseResultsBHBuyInner';
import { MovieWatchProviders200ResponseResultsMDFlatrateInner } from './movieWatchProviders200ResponseResultsMDFlatrateInner';


export interface MovieWatchProviders200ResponseResultsMD { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsBHBuyInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsMDFlatrateInner>;
}

