/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsPLFlatrateInner } from './movieWatchProviders200ResponseResultsPLFlatrateInner';
import { MovieWatchProviders200ResponseResultsAERentInner } from './movieWatchProviders200ResponseResultsAERentInner';


export interface MovieWatchProviders200ResponseResultsPL { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsPLFlatrateInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
}

