/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsPTRentInner } from './movieWatchProviders200ResponseResultsPTRentInner';
import { MovieWatchProviders200ResponseResultsPERentInner } from './movieWatchProviders200ResponseResultsPERentInner';
import { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './movieWatchProviders200ResponseResultsBEFlatrateInner';


export interface MovieWatchProviders200ResponseResultsPT { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsPTRentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
}

