/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsBERentInner } from './movieWatchProviders200ResponseResultsBERentInner';
import { MovieWatchProviders200ResponseResultsCARentInner } from './movieWatchProviders200ResponseResultsCARentInner';
import { MovieWatchProviders200ResponseResultsCAFlatrateInner } from './movieWatchProviders200ResponseResultsCAFlatrateInner';


export interface MovieWatchProviders200ResponseResultsCA { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsCARentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsCAFlatrateInner>;
}

