/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieReleaseDates200ResponseResultsInnerReleaseDatesInner } from './movieReleaseDates200ResponseResultsInnerReleaseDatesInner';


export interface MovieReleaseDates200ResponseResultsInner { 
    iso_3166_1?: string;
    release_dates?: Array<MovieReleaseDates200ResponseResultsInnerReleaseDatesInner>;
}

