/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsECBuyInner } from './movieWatchProviders200ResponseResultsECBuyInner';
import { MovieWatchProviders200ResponseResultsARFlatrateInner } from './movieWatchProviders200ResponseResultsARFlatrateInner';


export interface MovieWatchProviders200ResponseResultsEC { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsECBuyInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsARFlatrateInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsECBuyInner>;
}

