/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsIDFlatrateInner } from './movieWatchProviders200ResponseResultsIDFlatrateInner';


export interface MovieWatchProviders200ResponseResultsID { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsIDFlatrateInner>;
}

