/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsRURentInner } from './movieWatchProviders200ResponseResultsRURentInner';
import { MovieWatchProviders200ResponseResultsRUFlatrateInner } from './movieWatchProviders200ResponseResultsRUFlatrateInner';


export interface MovieWatchProviders200ResponseResultsRU { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsRURentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsRURentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsRUFlatrateInner>;
}

