/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsJPRentInner } from './movieWatchProviders200ResponseResultsJPRentInner';
import { MovieWatchProviders200ResponseResultsDKRentInner } from './movieWatchProviders200ResponseResultsDKRentInner';
import { MovieWatchProviders200ResponseResultsJPFlatrateInner } from './movieWatchProviders200ResponseResultsJPFlatrateInner';


export interface MovieWatchProviders200ResponseResultsJP { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsJPFlatrateInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsJPRentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsDKRentInner>;
}

