/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsMZRentInner } from './movieWatchProviders200ResponseResultsMZRentInner';


export interface MovieWatchProviders200ResponseResultsUG { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsMZRentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsMZRentInner>;
}

