/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieExternalIds200Response { 
    id?: number;
    imdb_id?: string;
    wikidata_id?: any | null;
    facebook_id?: string;
    instagram_id?: any | null;
    twitter_id?: any | null;
}

