/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieAlternativeTitles200ResponseTitlesInner } from './movieAlternativeTitles200ResponseTitlesInner';


export interface MovieAlternativeTitles200Response { 
    id?: number;
    titles?: Array<MovieAlternativeTitles200ResponseTitlesInner>;
}

