/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsPERentInner } from './movieWatchProviders200ResponseResultsPERentInner';
import { MovieWatchProviders200ResponseResultsARFlatrateInner } from './movieWatchProviders200ResponseResultsARFlatrateInner';


export interface MovieWatchProviders200ResponseResultsPE { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsARFlatrateInner>;
}

