/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieWatchProviders200ResponseResultsNLBuyInner { 
    logo_path?: string;
    provider_id?: number;
    provider_name?: string;
    display_priority?: number;
}

