/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './movieWatchProviders200ResponseResultsBEFlatrateInner';
import { MovieWatchProviders200ResponseResultsSEBuyInner } from './movieWatchProviders200ResponseResultsSEBuyInner';


export interface MovieWatchProviders200ResponseResultsSE { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsSEBuyInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsSEBuyInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
}

