/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieLatestId200Response { 
    adult?: boolean;
    backdrop_path?: any | null;
    belongs_to_collection?: any | null;
    budget?: number;
    genres?: Array<string>;
    homepage?: string;
    id?: number;
    imdb_id?: any | null;
    original_language?: string;
    original_title?: string;
    overview?: string;
    popularity?: number;
    poster_path?: any | null;
    production_companies?: Array<string>;
    production_countries?: Array<string>;
    release_date?: string;
    revenue?: number;
    runtime?: number;
    spoken_languages?: Array<string>;
    status?: string;
    tagline?: string;
    title?: string;
    video?: boolean;
    vote_average?: number;
    vote_count?: number;
}

