/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsALBuyInner } from './movieWatchProviders200ResponseResultsALBuyInner';
import { MovieWatchProviders200ResponseResultsMKFlatrateInner } from './movieWatchProviders200ResponseResultsMKFlatrateInner';


export interface MovieWatchProviders200ResponseResultsMK { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsALBuyInner>;
}

