/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsLIFlatrateInner } from './movieWatchProviders200ResponseResultsLIFlatrateInner';


export interface MovieWatchProviders200ResponseResultsSM { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsLIFlatrateInner>;
}

