/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieAccountStates200ResponseRated } from './movieAccountStates200ResponseRated';


export interface MovieAccountStates200Response { 
    id?: number;
    favorite?: boolean;
    rated?: MovieAccountStates200ResponseRated;
    watchlist?: boolean;
}

