/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieReleaseDates200ResponseResultsInnerReleaseDatesInner { 
    certification?: string;
    descriptors?: Array<string>;
    iso_639_1?: string;
    note?: string;
    release_date?: string;
    type?: number;
}

