/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsAUFlatrateInner } from './movieWatchProviders200ResponseResultsAUFlatrateInner';
import { MovieWatchProviders200ResponseResultsCOBuyInner } from './movieWatchProviders200ResponseResultsCOBuyInner';
import { MovieWatchProviders200ResponseResultsHRAdsInner } from './movieWatchProviders200ResponseResultsHRAdsInner';


export interface MovieWatchProviders200ResponseResultsHR { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsCOBuyInner>;
    ads?: Array<MovieWatchProviders200ResponseResultsHRAdsInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsAUFlatrateInner>;
}

