/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieUpcomingList200ResponseResultsInner } from './movieUpcomingList200ResponseResultsInner';
import { MovieUpcomingList200ResponseDates } from './movieUpcomingList200ResponseDates';


export interface MovieUpcomingList200Response { 
    dates?: MovieUpcomingList200ResponseDates;
    page?: number;
    results?: Array<MovieUpcomingList200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

