/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsARBuyInner } from './movieWatchProviders200ResponseResultsARBuyInner';
import { MovieWatchProviders200ResponseResultsARFlatrateInner } from './movieWatchProviders200ResponseResultsARFlatrateInner';


export interface MovieWatchProviders200ResponseResultsAR { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsARBuyInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsARFlatrateInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsARBuyInner>;
}

