/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieReviews200ResponseResultsInnerAuthorDetails } from './movieReviews200ResponseResultsInnerAuthorDetails';


export interface MovieReviews200ResponseResultsInner { 
    author?: string;
    author_details?: MovieReviews200ResponseResultsInnerAuthorDetails;
    content?: string;
    created_at?: string;
    id?: string;
    updated_at?: string;
    url?: string;
}

