/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsMUBuyInner } from './movieWatchProviders200ResponseResultsMUBuyInner';


export interface MovieWatchProviders200ResponseResultsMU { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsMUBuyInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsMUBuyInner>;
}

