/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './movieWatchProviders200ResponseResultsBEFlatrateInner';
import { MovieWatchProviders200ResponseResultsBERentInner } from './movieWatchProviders200ResponseResultsBERentInner';


export interface MovieWatchProviders200ResponseResultsNO { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;
}

