/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsCZBuyInner } from './movieWatchProviders200ResponseResultsCZBuyInner';
import { MovieWatchProviders200ResponseResultsARFlatrateInner } from './movieWatchProviders200ResponseResultsARFlatrateInner';


export interface MovieWatchProviders200ResponseResultsHU { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsARFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsCZBuyInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsCZBuyInner>;
}

