/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieNowPlayingList200ResponseDates } from './movieNowPlayingList200ResponseDates';
import { MovieNowPlayingList200ResponseResultsInner } from './movieNowPlayingList200ResponseResultsInner';


export interface MovieNowPlayingList200Response { 
    dates?: MovieNowPlayingList200ResponseDates;
    page?: number;
    results?: Array<MovieNowPlayingList200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

