/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsDEBuyInner } from './movieWatchProviders200ResponseResultsDEBuyInner';
import { MovieWatchProviders200ResponseResultsUSFlatrateInner } from './movieWatchProviders200ResponseResultsUSFlatrateInner';
import { MovieWatchProviders200ResponseResultsUSRentInner } from './movieWatchProviders200ResponseResultsUSRentInner';


export interface MovieWatchProviders200ResponseResultsUS { 
    link?: string;
    rent?: Array<MovieWatchProviders200ResponseResultsUSRentInner>;
    flatrate?: Array<MovieWatchProviders200ResponseResultsUSFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsDEBuyInner>;
}

