/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieLists200ResponseResultsInner { 
    description?: string;
    favorite_count?: number;
    id?: number;
    item_count?: number;
    iso_639_1?: string;
    list_type?: string;
    name?: string;
    poster_path?: any | null;
}

