/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsAEFlatrateInner } from './movieWatchProviders200ResponseResultsAEFlatrateInner';
import { MovieWatchProviders200ResponseResultsAERentInner } from './movieWatchProviders200ResponseResultsAERentInner';


export interface MovieWatchProviders200ResponseResultsAE { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsAEFlatrateInner>;
    rent?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsAERentInner>;
}

