/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieTranslations200ResponseTranslationsInner } from './movieTranslations200ResponseTranslationsInner';


export interface MovieTranslations200Response { 
    id?: number;
    translations?: Array<MovieTranslations200ResponseTranslationsInner>;
}

