/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NetworkDetails200Response { 
    headquarters?: string;
    homepage?: string;
    id?: number;
    logo_path?: string;
    name?: string;
    origin_country?: string;
}

