/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonChanges200ResponseChangesInnerItemsInner { 
    id?: string;
    action?: string;
    time?: string;
    iso_639_1?: string;
    iso_3166_1?: string;
    value?: string;
}

