/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonChanges200ResponseChangesInnerItemsInner } from './personChanges200ResponseChangesInnerItemsInner';


export interface PersonChanges200ResponseChangesInner { 
    key?: string;
    items?: Array<PersonChanges200ResponseChangesInnerItemsInner>;
}

