/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonTaggedImages200ResponseResultsInnerMedia } from './personTaggedImages200ResponseResultsInnerMedia';


export interface PersonTaggedImages200ResponseResultsInner { 
    aspect_ratio?: number;
    file_path?: string;
    height?: number;
    id?: string;
    iso_639_1?: string;
    vote_average?: number;
    vote_count?: number;
    width?: number;
    image_type?: string;
    media?: PersonTaggedImages200ResponseResultsInnerMedia;
    media_type?: string;
}

