/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonCombinedCredits200ResponseCastInner } from './personCombinedCredits200ResponseCastInner';
import { PersonCombinedCredits200ResponseCrewInner } from './personCombinedCredits200ResponseCrewInner';


export interface PersonCombinedCredits200Response { 
    cast?: Array<PersonCombinedCredits200ResponseCastInner>;
    crew?: Array<PersonCombinedCredits200ResponseCrewInner>;
    id?: number;
}

