/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonMovieCredits200ResponseCrewInner } from './personMovieCredits200ResponseCrewInner';
import { PersonMovieCredits200ResponseCastInner } from './personMovieCredits200ResponseCastInner';


export interface PersonMovieCredits200Response { 
    cast?: Array<PersonMovieCredits200ResponseCastInner>;
    crew?: Array<PersonMovieCredits200ResponseCrewInner>;
    id?: number;
}

