/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonExternalIds200Response { 
    id?: number;
    freebase_mid?: string;
    freebase_id?: string;
    imdb_id?: string;
    tvrage_id?: number;
    wikidata_id?: string;
    facebook_id?: string;
    instagram_id?: string;
    tiktok_id?: string;
    twitter_id?: string;
    youtube_id?: any | null;
}

