/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonLatestId200Response { 
    adult?: boolean;
    also_known_as?: Array<string>;
    biography?: string;
    birthday?: any | null;
    deathday?: any | null;
    gender?: number;
    homepage?: any | null;
    id?: number;
    imdb_id?: any | null;
    known_for_department?: any | null;
    name?: string;
    place_of_birth?: any | null;
    popularity?: number;
    profile_path?: any | null;
}

