/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonTvCredits200ResponseCastInner } from './personTvCredits200ResponseCastInner';
import { PersonTvCredits200ResponseCrewInner } from './personTvCredits200ResponseCrewInner';


export interface PersonTvCredits200Response { 
    cast?: Array<PersonTvCredits200ResponseCastInner>;
    crew?: Array<PersonTvCredits200ResponseCrewInner>;
    id?: number;
}

