/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonTaggedImages200ResponseResultsInner } from './personTaggedImages200ResponseResultsInner';


export interface PersonTaggedImages200Response { 
    id?: number;
    page?: number;
    results?: Array<PersonTaggedImages200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

