/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDetails200ResponseAuthorDetails } from './reviewDetails200ResponseAuthorDetails';


export interface ReviewDetails200Response { 
    id?: string;
    author?: string;
    author_details?: ReviewDetails200ResponseAuthorDetails;
    content?: string;
    created_at?: string;
    iso_639_1?: string;
    media_id?: number;
    media_title?: string;
    media_type?: string;
    updated_at?: string;
    url?: string;
}

