/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchMulti200ResponseResultsInner { 
    adult?: boolean;
    backdrop_path?: string;
    id?: number;
    title?: string;
    original_language?: string;
    original_title?: string;
    overview?: string;
    poster_path?: string;
    media_type?: string;
    genre_ids?: Array<number>;
    popularity?: number;
    release_date?: string;
    video?: boolean;
    vote_average?: number;
    vote_count?: number;
}

