/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Translations200ResponseTranslationsInnerData } from './translations200ResponseTranslationsInnerData';


export interface Translations200ResponseTranslationsInner { 
    iso_3166_1?: string;
    iso_639_1?: string;
    name?: string;
    english_name?: string;
    data?: Translations200ResponseTranslationsInnerData;
}

