/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendingPeople200ResponseResultsInnerKnownForInner } from './trendingPeople200ResponseResultsInnerKnownForInner';


export interface TrendingPeople200ResponseResultsInner { 
    adult?: boolean;
    id?: number;
    name?: string;
    original_name?: string;
    media_type?: string;
    popularity?: number;
    gender?: number;
    known_for_department?: string;
    profile_path?: string;
    known_for?: Array<TrendingPeople200ResponseResultsInnerKnownForInner>;
}

