/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeChangesById200ResponseChangesInner } from './tvEpisodeChangesById200ResponseChangesInner';


export interface TvEpisodeChangesById200Response { 
    changes?: Array<TvEpisodeChangesById200ResponseChangesInner>;
}

