/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeTranslations200ResponseTranslationsInner } from './tvEpisodeTranslations200ResponseTranslationsInner';


export interface TvEpisodeTranslations200Response { 
    id?: number;
    translations?: Array<TvEpisodeTranslations200ResponseTranslationsInner>;
}

