/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeImages200ResponseStillsInner } from './tvEpisodeImages200ResponseStillsInner';


export interface TvEpisodeImages200Response { 
    id?: number;
    stills?: Array<TvEpisodeImages200ResponseStillsInner>;
}

