/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner } from './tvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner';


export interface TvEpisodeGroupDetails200ResponseGroupsInner { 
    id?: string;
    name?: string;
    order?: number;
    episodes?: Array<TvEpisodeGroupDetails200ResponseGroupsInnerEpisodesInner>;
    locked?: boolean;
}

