/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeDetails200ResponseCrewInner } from './tvEpisodeDetails200ResponseCrewInner';
import { TvEpisodeDetails200ResponseGuestStarsInner } from './tvEpisodeDetails200ResponseGuestStarsInner';


export interface TvEpisodeDetails200Response { 
    air_date?: string;
    crew?: Array<TvEpisodeDetails200ResponseCrewInner>;
    episode_number?: number;
    guest_stars?: Array<TvEpisodeDetails200ResponseGuestStarsInner>;
    name?: string;
    overview?: string;
    id?: number;
    production_code?: string;
    runtime?: number;
    season_number?: number;
    still_path?: string;
    vote_average?: number;
    vote_count?: number;
}

