/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisodeGroupDetails200ResponseNetwork } from './tvEpisodeGroupDetails200ResponseNetwork';
import { TvEpisodeGroupDetails200ResponseGroupsInner } from './tvEpisodeGroupDetails200ResponseGroupsInner';


export interface TvEpisodeGroupDetails200Response { 
    description?: string;
    episode_count?: number;
    group_count?: number;
    groups?: Array<TvEpisodeGroupDetails200ResponseGroupsInner>;
    id?: string;
    name?: string;
    network?: TvEpisodeGroupDetails200ResponseNetwork;
    type?: number;
}

