/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesAggregateCredits200ResponseCastInner } from './tvSeriesAggregateCredits200ResponseCastInner';
import { TvSeriesAggregateCredits200ResponseCrewInner } from './tvSeriesAggregateCredits200ResponseCrewInner';


export interface TvSeriesAggregateCredits200Response { 
    cast?: Array<TvSeriesAggregateCredits200ResponseCastInner>;
    crew?: Array<TvSeriesAggregateCredits200ResponseCrewInner>;
    id?: number;
}

