/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesAggregateCredits200ResponseCastInnerRolesInner } from './tvSeriesAggregateCredits200ResponseCastInnerRolesInner';


export interface TvSeriesAggregateCredits200ResponseCastInner { 
    adult?: boolean;
    gender?: number;
    id?: number;
    known_for_department?: string;
    name?: string;
    original_name?: string;
    popularity?: number;
    profile_path?: string;
    roles?: Array<TvSeriesAggregateCredits200ResponseCastInnerRolesInner>;
    total_episode_count?: number;
    order?: number;
}

