/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsRUFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsRUFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsRU { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsRUFlatrateInner>;
}

