/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsCOFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCOFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsCO { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCOFlatrateInner>;
}

