/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsEGFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsEGFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsEG { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsEGFlatrateInner>;
}

