/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesChanges200ResponseChangesInnerItemsInnerValue } from './tvSeriesChanges200ResponseChangesInnerItemsInnerValue';
import { TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue } from './tvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue';


export interface TvSeriesChanges200ResponseChangesInnerItemsInner { 
    id?: string;
    action?: string;
    time?: string;
    iso_639_1?: string;
    iso_3166_1?: string;
    value?: TvSeriesChanges200ResponseChangesInnerItemsInnerValue;
    original_value?: TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue;
}

