/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsDEBuyInner } from './movieWatchProviders200ResponseResultsDEBuyInner';
import { TvSeriesWatchProviders200ResponseResultsDEFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsDEFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsDE { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsDEBuyInner>;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsDEFlatrateInner>;
}

