/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsGFFlatrateInner } from './movieWatchProviders200ResponseResultsGFFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsGF { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsGFFlatrateInner>;
}

