/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonTranslations200ResponseTranslationsInner } from './tvSeasonTranslations200ResponseTranslationsInner';


export interface TvSeasonTranslations200Response { 
    id?: number;
    translations?: Array<TvSeasonTranslations200ResponseTranslationsInner>;
}

