/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesEpisodeGroups200ResponseResultsInner } from './tvSeriesEpisodeGroups200ResponseResultsInner';


export interface TvSeriesEpisodeGroups200Response { 
    results?: Array<TvSeriesEpisodeGroups200ResponseResultsInner>;
    id?: number;
}

