/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonChangesById200ResponseChangesInnerItemsInnerValue } from './tvSeasonChangesById200ResponseChangesInnerItemsInnerValue';


export interface TvSeasonChangesById200ResponseChangesInnerItemsInner { 
    id?: string;
    action?: string;
    time?: string;
    value?: TvSeasonChangesById200ResponseChangesInnerItemsInnerValue;
}

