/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonImages200ResponsePostersInner } from './tvSeasonImages200ResponsePostersInner';


export interface TvSeasonImages200Response { 
    id?: number;
    posters?: Array<TvSeasonImages200ResponsePostersInner>;
}

