/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResults } from './tvSeriesWatchProviders200ResponseResults';


export interface TvSeriesWatchProviders200Response { 
    id?: number;
    results?: TvSeriesWatchProviders200ResponseResults;
}

