/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesLatestId200ResponseSeasonsInner } from './tvSeriesLatestId200ResponseSeasonsInner';
import { TvSeriesLatestId200ResponseLastEpisodeToAir } from './tvSeriesLatestId200ResponseLastEpisodeToAir';


export interface TvSeriesLatestId200Response { 
    adult?: boolean;
    backdrop_path?: any | null;
    created_by?: Array<string>;
    episode_run_time?: Array<string>;
    first_air_date?: string;
    genres?: Array<string>;
    homepage?: string;
    id?: number;
    in_production?: boolean;
    languages?: Array<string>;
    last_air_date?: string;
    last_episode_to_air?: TvSeriesLatestId200ResponseLastEpisodeToAir;
    name?: string;
    next_episode_to_air?: any | null;
    networks?: Array<string>;
    number_of_episodes?: number;
    number_of_seasons?: number;
    origin_country?: Array<string>;
    original_language?: string;
    original_name?: string;
    overview?: string;
    popularity?: number;
    poster_path?: any | null;
    production_companies?: Array<string>;
    production_countries?: Array<string>;
    seasons?: Array<TvSeriesLatestId200ResponseSeasonsInner>;
    spoken_languages?: Array<string>;
    status?: string;
    tagline?: string;
    type?: string;
    vote_average?: number;
    vote_count?: number;
}

