/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsIEFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsIEFlatrateInner';
import { TvSeriesWatchProviders200ResponseResultsIEBuyInner } from './tvSeriesWatchProviders200ResponseResultsIEBuyInner';


export interface TvSeasonWatchProviders200ResponseResultsIE { 
    link?: string;
    buy?: Array<TvSeriesWatchProviders200ResponseResultsIEBuyInner>;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsIEFlatrateInner>;
}

