/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsDEBuyInner } from './movieWatchProviders200ResponseResultsDEBuyInner';
import { TvSeriesWatchProviders200ResponseResultsBRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsBRFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsUS { 
    link?: string;
    buy?: Array<MovieWatchProviders200ResponseResultsDEBuyInner>;
    free?: Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>;
}

