/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsFRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsFRFlatrateInner';
import { MovieWatchProviders200ResponseResultsFRRentInner } from './movieWatchProviders200ResponseResultsFRRentInner';


export interface TvSeasonWatchProviders200ResponseResultsFR { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsFRFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsFRRentInner>;
}

