/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsARFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsARFlatrateInner';
import { TvSeriesWatchProviders200ResponseResultsNOBuyInner } from './tvSeriesWatchProviders200ResponseResultsNOBuyInner';


export interface TvSeasonWatchProviders200ResponseResultsNO { 
    link?: string;
    buy?: Array<TvSeriesWatchProviders200ResponseResultsNOBuyInner>;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsARFlatrateInner>;
}

