/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonChangesById200ResponseChangesInner } from './tvSeasonChangesById200ResponseChangesInner';


export interface TvSeasonChangesById200Response { 
    changes?: Array<TvSeasonChangesById200ResponseChangesInner>;
}

