/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesDetails200ResponseNetworksInner } from './tvSeriesDetails200ResponseNetworksInner';


export interface TvSeriesEpisodeGroups200ResponseResultsInner { 
    description?: string;
    episode_count?: number;
    group_count?: number;
    id?: string;
    name?: string;
    network?: TvSeriesDetails200ResponseNetworksInner;
    type?: number;
}

