/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesCredits200ResponseCrewInner } from './tvSeriesCredits200ResponseCrewInner';
import { TvSeriesCredits200ResponseCastInner } from './tvSeriesCredits200ResponseCastInner';


export interface TvSeriesCredits200Response { 
    cast?: Array<TvSeriesCredits200ResponseCastInner>;
    crew?: Array<TvSeriesCredits200ResponseCrewInner>;
    id?: number;
}

