/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieKeywords200ResponseKeywordsInner } from './movieKeywords200ResponseKeywordsInner';


export interface TvSeriesKeywords200Response { 
    id?: number;
    results?: Array<MovieKeywords200ResponseKeywordsInner>;
}

