/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsSAFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsSAFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsSA { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsSAFlatrateInner>;
}

