/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonCredits200ResponseCrewInner } from './tvSeasonCredits200ResponseCrewInner';
import { TvSeriesCredits200ResponseCastInner } from './tvSeriesCredits200ResponseCastInner';


export interface TvSeasonCredits200Response { 
    cast?: Array<TvSeriesCredits200ResponseCastInner>;
    crew?: Array<TvSeasonCredits200ResponseCrewInner>;
    id?: number;
}

