/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsAUBuyInner } from './movieWatchProviders200ResponseResultsAUBuyInner';
import { TvSeriesWatchProviders200ResponseResultsAUFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsAUFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsAU { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsAUFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsAUBuyInner>;
}

