/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsGBBuyInner } from './movieWatchProviders200ResponseResultsGBBuyInner';
import { TvSeriesWatchProviders200ResponseResultsGBFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsGBFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsGB { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsGBFlatrateInner>;
    buy?: Array<MovieWatchProviders200ResponseResultsGBBuyInner>;
}

