/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsKEFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsKEFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsMZ { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsKEFlatrateInner>;
}

