/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster } from './tvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster';


export interface TvSeriesChanges200ResponseChangesInnerItemsInnerValue { 
    poster?: TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster;
}

