/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsESFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsESFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsES { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsESFlatrateInner>;
}

