/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonDetails200ResponseEpisodesInner } from './tvSeasonDetails200ResponseEpisodesInner';


export interface TvSeasonDetails200Response { 
    _id?: string;
    air_date?: string;
    episodes?: Array<TvSeasonDetails200ResponseEpisodesInner>;
    name?: string;
    overview?: string;
    id?: number;
    poster_path?: string;
    season_number?: number;
    vote_average?: number;
}

