/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonAggregateCredits200ResponseCastInner } from './tvSeasonAggregateCredits200ResponseCastInner';
import { TvSeasonAggregateCredits200ResponseCrewInner } from './tvSeasonAggregateCredits200ResponseCrewInner';


export interface TvSeasonAggregateCredits200Response { 
    cast?: Array<TvSeasonAggregateCredits200ResponseCastInner>;
    crew?: Array<TvSeasonAggregateCredits200ResponseCrewInner>;
    id?: number;
}

