/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsGHFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsGHFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsGH { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>;
}

