/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvSeasonImages200ResponsePostersInner { 
    aspect_ratio?: number;
    height?: number;
    iso_639_1?: string;
    file_path?: string;
    vote_average?: number;
    vote_count?: number;
    width?: number;
}

