/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesTranslations200ResponseTranslationsInnerData } from './tvSeriesTranslations200ResponseTranslationsInnerData';


export interface TvSeriesTranslations200ResponseTranslationsInner { 
    iso_3166_1?: string;
    iso_639_1?: string;
    name?: string;
    english_name?: string;
    data?: TvSeriesTranslations200ResponseTranslationsInnerData;
}

