/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsTTFlatrateInner } from './movieWatchProviders200ResponseResultsTTFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsTT { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsTTFlatrateInner>;
}

