/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesScreenedTheatrically200ResponseResultsInner } from './tvSeriesScreenedTheatrically200ResponseResultsInner';


export interface TvSeriesScreenedTheatrically200Response { 
    id?: number;
    results?: Array<TvSeriesScreenedTheatrically200ResponseResultsInner>;
}

