/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities } from './watchProvidersMovieList200ResponseResultsInnerDisplayPriorities';


export interface WatchProvidersMovieList200ResponseResultsInner { 
    display_priorities?: WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities;
    display_priority?: number;
    logo_path?: string;
    provider_name?: string;
    provider_id?: number;
}

