/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WatchProvidersAvailableRegions200ResponseResultsInner } from './watchProvidersAvailableRegions200ResponseResultsInner';


export interface WatchProvidersAvailableRegions200Response { 
    results?: Array<WatchProvidersAvailableRegions200ResponseResultsInner>;
}

